---
- name: Configurar e fazer deploy da aplicação
  hosts: web
  become: true
  tasks:

    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar dependências para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: latest

    - name: Instalar Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Garantir que o serviço Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Parar container antigo (se existir)
      shell: docker compose down
      args:
        chdir: /home/gabriel/app
      ignore_errors: true

    - name: Clonar repositório do projeto
      git:
        repo: 'https://github.com/GabrielBogo1/frontend-mensal'
        dest: /home/gabriel/app/

    - name: Rebuildar imagem e subir container atualizado
      shell: docker compose up -d --build
      args:
        chdir: /home/gabriel/app
